# Generated by Django 4.1.1 on 2022-09-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevent_measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventmeasure',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
