# Generated by Django 4.1.1 on 2022-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect', '0002_alter_insect_insect_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insect',
            name='insect_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/insects/'),
        ),
    ]
