# Generated by Django 4.1.1 on 2022-09-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('organic_control', models.TextField()),
                ('link', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('insect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insect.insect')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('symptom_image', models.ImageField(upload_to='symptom-images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('infestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infestation.infestation')),
            ],
        ),
        migrations.CreateModel(
            name='PreventMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('prevent_image', models.ImageField(upload_to='prevent-images/')),
                ('link', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('infestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infestation.infestation')),
            ],
        ),
    ]
