# Generated by Django 4.1.1 on 2022-09-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('infestation', '0002_remove_preventmeasure_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infestation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='infestation',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='infestation',
            name='recommendation_description',
            field=models.TextField(default='sample'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infestation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.recommendation'),
        ),
    ]
