# Generated by Django 4.1.1 on 2022-09-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0004_alter_preventmeasure_prevent_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='date_updated',
        ),
    ]
