# Generated by Django 4.1.1 on 2022-09-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_recommendationseasons_recommendation'),
        ('infestation', '0005_remove_symptom_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infestation',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_infestation', to='recommendation.recommendation'),
        ),
    ]
