# Generated by Django 4.1.1 on 2022-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0006_alter_infestation_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventmeasure',
            name='infestation',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='infestation',
        ),
        migrations.AddField(
            model_name='infestation',
            name='prevent_measures',
            field=models.ManyToManyField(to='infestation.preventmeasure'),
        ),
        migrations.AddField(
            model_name='infestation',
            name='symptoms',
            field=models.ManyToManyField(to='infestation.symptom'),
        ),
    ]
