# Generated by Django 4.1.1 on 2022-09-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0007_remove_preventmeasure_infestation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infestation',
            name='prevent_measures',
        ),
        migrations.RemoveField(
            model_name='infestation',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='preventmeasure',
            name='infestation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infestation.infestation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='infestation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='infestation.infestation'),
            preserve_default=False,
        ),
    ]
