# Generated by Django 4.1.1 on 2022-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0008_remove_infestation_prevent_measures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventmeasure',
            name='prevent_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/prevents'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/symptoms'),
        ),
    ]
