# Generated by Django 4.0.6 on 2022-12-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0010_alter_preventmeasure_infestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infestation',
            name='insect_stage',
            field=models.CharField(choices=[('FLOWERING', 'Flowering'), ('HARVESTING', 'Harvesting'), ('N/A', 'N/A')], default='N/A', max_length=100),
        ),
    ]
