# Generated by Django 4.1.1 on 2022-09-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insecticide', '0001_initial'),
        ('infestation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.TextField()),
                ('link', models.TextField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=0, max_digits=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('infestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infestation.infestation')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalSafetyPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(upload_to='icon-images/')),
                ('link', models.TextField(blank=True, null=True)),
                ('hazard_level', models.CharField(choices=[('LOW', 'Low Toxic'), ('MODERATE', 'Moderate Toxic'), ('HIGH', 'High Toxic'), ('N/A', 'N/A')], default='N/A', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chemical_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_control.chemicalcontrol')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(upload_to='icon-images/')),
                ('link', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chemical_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_control.chemicalcontrol')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalInsecticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chemical_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_control.chemicalcontrol')),
                ('insecticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insecticide.insecticide')),
            ],
        ),
    ]
