# Generated by Django 4.1.1 on 2022-09-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalcontrol',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chemicalcontrol',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='chemicalinsecticide',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chemicalinsecticide',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='chemicalinstruction',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chemicalinstruction',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='chemicalsafetyprecaution',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chemicalsafetyprecaution',
            name='date_updated',
        ),
    ]
