# Generated by Django 4.1.1 on 2022-09-18 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_control', '0002_alter_chemicalcontrol_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalcontrol',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalcontrol',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chemicalinsecticide',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalinsecticide',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
