# Generated by Django 4.1.1 on 2022-09-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0008_remove_infestation_prevent_measures_and_more'),
        ('chemical_control', '0003_alter_chemicalinstruction_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalcontrol',
            name='infestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_control_infestation', to='infestation.infestation'),
        ),
    ]
