# Generated by Django 4.1.1 on 2022-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_control', '0004_alter_chemicalcontrol_infestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalcontrol',
            name='percentage',
        ),
        migrations.AddField(
            model_name='chemicalinsecticide',
            name='percentage',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=3),
            preserve_default=False,
        ),
    ]
