# Generated by Django 4.1.1 on 2022-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_control', '0005_remove_chemicalcontrol_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalinstruction',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
        migrations.AlterField(
            model_name='chemicalsafetyprecaution',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/'),
        ),
    ]
