# Generated by Django 4.1 on 2022-09-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_control', '0006_alter_chemicalinstruction_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalinsecticide',
            name='chemical_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_control_insecticide', to='chemical_control.chemicalcontrol'),
        ),
        migrations.AlterField(
            model_name='chemicalinstruction',
            name='chemical_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_control_instruction', to='chemical_control.chemicalcontrol'),
        ),
        migrations.AlterField(
            model_name='chemicalsafetyprecaution',
            name='chemical_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_control_precaution', to='chemical_control.chemicalcontrol'),
        ),
    ]
