# Generated by Django 4.1 on 2022-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_control', '0007_alter_chemicalinsecticide_chemical_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalsafetyprecaution',
            name='hazard_level',
        ),
        migrations.AddField(
            model_name='chemicalcontrol',
            name='hazard_level',
            field=models.CharField(choices=[('LOW', 'Low Toxic'), ('MODERATE', 'Moderate Toxic'), ('HIGH', 'High Toxic'), ('N/A', 'N/A')], default='N/A', max_length=100),
        ),
    ]
