# Generated by Django 4.1 on 2022-09-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_agriculturetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='agriculture_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/agriculture/'),
        ),
        migrations.AddField(
            model_name='agriculturetype',
            name='agriculture_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/agriculture-type/'),
        ),
    ]
