# Generated by Django 4.1.1 on 2022-09-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DRY', 'Dry'), ('WET', 'Wet'), ('N/A', 'N/A')], default='N/A', max_length=100)),
                ('description', models.TextField()),
                ('season_image', models.ImageField(upload_to='season-images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
