# Generated by Django 4.1.1 on 2022-09-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='season',
            name='date_updated',
        ),
    ]
