# Generated by Django 4.1.1 on 2022-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_remove_season_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_image',
            field=models.ImageField(blank=True, null=True, upload_to='season-images/'),
        ),
    ]
