# Generated by Django 4.1.1 on 2022-09-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_rename_author_recommendationseasons_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='date_updated',
        ),
    ]
