# Generated by Django 4.1.1 on 2022-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_recommendationseasons_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationseasons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recommendation-season-photos/'),
        ),
    ]
