# Generated by Django 4.1 on 2022-09-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_agriculturetype'),
        ('recommendation', '0007_alter_recommendation_agriculture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='agriculture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='agriculture_type', to='agriculture.agriculturetype'),
        ),
    ]
