# Generated by Django 4.1 on 2022-09-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_alter_recommendation_agriculture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
